remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Information Technology for Logistics (Nirand)]
description: [Information Technology for Logistics (Nirand)]
